version: "3"

services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-tier
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-tier
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:  # Define health check for MySQL service
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u${DB_USER}", "-p${DB_PASS}"]
      interval: 10s  # Check every 10 seconds
      timeout: 5s   # Timeout after 5 seconds
      retries: 5    # Retry 5 times before considering the service unhealthy

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - mysql
volumes:
  db-data:
networks:
  app-tier:
